import { Badge, Button, Group, Paper, Stack, Text } from "@mantine/core";
import { IconSparkles } from "@tabler/icons-react";
import type { InsightSummary } from "../types";

type InsightListProps = {
  insights: InsightSummary[];
  canRefresh: boolean;
  onRefresh: () => Promise<void> | void;
};

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

export function InsightList({ insights, canRefresh, onRefresh }: InsightListProps) {
  return (
    <Paper withBorder radius="lg" p="md" className="panel-surface">
      <Stack gap="sm">
        <Group justify="space-between">
          <div>
            <Text fw={700}>Saved insights</Text>
            <Text c="dimmed" size="sm">
              Refresh to reload the files generated by the background insight scheduler.
            </Text>
          </div>
          <Button variant="light" size="xs" onClick={() => void onRefresh()} disabled={!canRefresh}>
            Refresh
          </Button>
        </Group>

        {insights.length === 0 ? (
          <Text c="dimmed" size="sm">
            No insight files have been saved for this session yet.
          </Text>
        ) : (
          insights.map((insight) => (
            <Paper key={insight.path} withBorder radius="md" p="sm" className="insight-card">
              <Stack gap={4}>
                <Group gap="xs" wrap="wrap">
                  <Badge leftSection={<IconSparkles size={12} />} variant="light" color="teal">
                    {insight.model ?? "Risk insight"}
                  </Badge>
                  <Badge variant="outline">{formatDate(insight.created_at)}</Badge>
                </Group>
                <Text fw={600} size="sm">
                  {insight.file_name}
                </Text>
                <Text size="sm" c="dimmed">
                  {insight.excerpt ?? "Insight stored on disk."}
                </Text>
              </Stack>
            </Paper>
          ))
        )}
      </Stack>
    </Paper>
  );
}

