import { Badge, Button, Group, Paper, Stack, Text } from "@mantine/core";
import { IconSparkles } from "@tabler/icons-react";
import type { InsightSummary } from "../types";

type InsightListProps = {
  insights: InsightSummary[];
  canRefresh: boolean;
  onRefresh: () => Promise<void> | void;
};

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

export function InsightList({ insights, canRefresh, onRefresh }: InsightListProps) {
  return (
    <Paper withBorder radius="xl" p="lg" className="panel-surface">
      <Stack gap="md">
        <Group justify="space-between">
          <div>
            <Text fw={700} size="lg">
              Saved insights
            </Text>
            <Text c="dimmed" size="sm">
              Refresh to reload the files generated by the background insight scheduler.
            </Text>
          </div>
          <Group gap="xs">
            <Badge variant="light" color="grape">
              {insights.length} file{insights.length === 1 ? "" : "s"}
            </Badge>
            <Button variant="light" size="xs" onClick={() => void onRefresh()} disabled={!canRefresh}>
              Refresh
            </Button>
          </Group>
        </Group>

        {insights.length === 0 ? (
          <div className="empty-state">
            <Text fw={600}>No insight files yet</Text>
            <Text c="dimmed" size="sm">
              Keep the session open long enough for the scheduler to write files, then refresh this list.
            </Text>
          </div>
        ) : (
          insights.map((insight) => (
            <Paper key={insight.path} withBorder radius="md" p="sm" className="insight-card">
              <Stack gap={4}>
                <Group gap="xs" wrap="wrap">
                  <Badge leftSection={<IconSparkles size={12} />} variant="light" color="teal">
                    {insight.model ?? "Risk insight"}
                  </Badge>
                  <Badge variant="outline">{formatDate(insight.created_at)}</Badge>
                </Group>
                <Text fw={600} size="sm">
                  {insight.file_name}
                </Text>
                <Text size="sm" c="dimmed">
                  {insight.excerpt ?? "Insight stored on disk."}
                </Text>
              </Stack>
            </Paper>
          ))
        )}
      </Stack>
    </Paper>
  );
}
